### ISSUE TITLE
Incorrect delimiter for my Unicorn export

### ISSUE THREAD

**Issue by BlueDrink9** [sami-chaaban/PlotAkta#2]
Can't recall what version of Unicorn it was, but I got a CSV that was comma delimated, whereas your script expects tabs. Easy fix for me, but I thought I'd make note of it if others are using it.

I also get a CSV output that has no BOM, so `open` is having trouble reading it.

**Comment by camillaadan** [comment]
"I'm experiencing an error message that says 'ERROR: No 'UV 1_280' (UV trace) column in the CSV file' when I try to read a tab-delimited UTF-16 file. However, I am certain that the file contains this column. Could you please provide me with an example input file so that I can test my code and figure out what might be causing this error?"
